/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TosRouteImport } from './routes/tos'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as WidgetLoginRouteImport } from './routes/widget-login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminInstanceRouteRouteImport } from './routes/admin/instance/route'
import { Route as AdminInstanceIndexRouteImport } from './routes/admin/instance/index'
import { Route as AdminInstanceAuditRouteImport } from './routes/admin/instance/audit'
import { Route as AdminInstanceMailRouteImport } from './routes/admin/instance/mail'
import { Route as AdminInstanceOverviewRouteImport } from './routes/admin/instance/overview'
import { Route as AdminInstanceSettingsRouteImport } from './routes/admin/instance/settings'
import { Route as AdminInstanceSitesRouteImport } from './routes/admin/instance/sites'
import { Route as AdminInstanceUsersRouteImport } from './routes/admin/instance/users'
import { Route as AdminSiteSiteIdRouteRouteImport } from './routes/admin/site/$siteId/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AdminSiteSiteIdCommentsRouteImport } from './routes/admin/site/$siteId/comments'
import { Route as AdminSiteSiteIdIntegrationRouteImport } from './routes/admin/site/$siteId/integration'
import { Route as AdminSiteSiteIdMembersRouteImport } from './routes/admin/site/$siteId/members'
import { Route as AdminSiteSiteIdSettingsRouteImport } from './routes/admin/site/$siteId/settings'
import { Route as AdminSiteSiteIdStatisticsRouteImport } from './routes/admin/site/$siteId/statistics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetLoginRoute = WidgetLoginRouteImport.update({
  id: '/widget-login',
  path: '/widget-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstanceRouteRoute = AdminInstanceRouteRouteImport.update({
  id: '/instance',
  path: '/instance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstanceIndexRoute = AdminInstanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceAuditRoute = AdminInstanceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceMailRoute = AdminInstanceMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceOverviewRoute = AdminInstanceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceSettingsRoute = AdminInstanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceSitesRoute = AdminInstanceSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminInstanceUsersRoute = AdminInstanceUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminInstanceRouteRoute,
} as any)
const AdminSiteSiteIdRouteRoute = AdminSiteSiteIdRouteRouteImport.update({
  id: '/site/$siteId',
  path: '/site/$siteId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSiteSiteIdCommentsRoute = AdminSiteSiteIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminSiteSiteIdRouteRoute,
} as any)
const AdminSiteSiteIdIntegrationRoute =
  AdminSiteSiteIdIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AdminSiteSiteIdRouteRoute,
  } as any)
const AdminSiteSiteIdMembersRoute = AdminSiteSiteIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminSiteSiteIdRouteRoute,
} as any)
const AdminSiteSiteIdSettingsRoute = AdminSiteSiteIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminSiteSiteIdRouteRoute,
} as any)
const AdminSiteSiteIdStatisticsRoute =
  AdminSiteSiteIdStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AdminSiteSiteIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tos': typeof TosRoute
  '/widget': typeof WidgetRoute
  '/widget-login': typeof WidgetLoginRoute
  '/admin/instance': typeof AdminInstanceRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/site/$siteId': typeof AdminSiteSiteIdRouteRouteWithChildren
  '/admin/instance/audit': typeof AdminInstanceAuditRoute
  '/admin/instance/mail': typeof AdminInstanceMailRoute
  '/admin/instance/overview': typeof AdminInstanceOverviewRoute
  '/admin/instance/settings': typeof AdminInstanceSettingsRoute
  '/admin/instance/sites': typeof AdminInstanceSitesRoute
  '/admin/instance/users': typeof AdminInstanceUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/instance/': typeof AdminInstanceIndexRoute
  '/admin/site/$siteId/comments': typeof AdminSiteSiteIdCommentsRoute
  '/admin/site/$siteId/integration': typeof AdminSiteSiteIdIntegrationRoute
  '/admin/site/$siteId/members': typeof AdminSiteSiteIdMembersRoute
  '/admin/site/$siteId/settings': typeof AdminSiteSiteIdSettingsRoute
  '/admin/site/$siteId/statistics': typeof AdminSiteSiteIdStatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tos': typeof TosRoute
  '/widget': typeof WidgetRoute
  '/widget-login': typeof WidgetLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/site/$siteId': typeof AdminSiteSiteIdRouteRouteWithChildren
  '/admin/instance/audit': typeof AdminInstanceAuditRoute
  '/admin/instance/mail': typeof AdminInstanceMailRoute
  '/admin/instance/overview': typeof AdminInstanceOverviewRoute
  '/admin/instance/settings': typeof AdminInstanceSettingsRoute
  '/admin/instance/sites': typeof AdminInstanceSitesRoute
  '/admin/instance/users': typeof AdminInstanceUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/instance': typeof AdminInstanceIndexRoute
  '/admin/site/$siteId/comments': typeof AdminSiteSiteIdCommentsRoute
  '/admin/site/$siteId/integration': typeof AdminSiteSiteIdIntegrationRoute
  '/admin/site/$siteId/members': typeof AdminSiteSiteIdMembersRoute
  '/admin/site/$siteId/settings': typeof AdminSiteSiteIdSettingsRoute
  '/admin/site/$siteId/statistics': typeof AdminSiteSiteIdStatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tos': typeof TosRoute
  '/widget': typeof WidgetRoute
  '/widget-login': typeof WidgetLoginRoute
  '/admin/instance': typeof AdminInstanceRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/site/$siteId': typeof AdminSiteSiteIdRouteRouteWithChildren
  '/admin/instance/audit': typeof AdminInstanceAuditRoute
  '/admin/instance/mail': typeof AdminInstanceMailRoute
  '/admin/instance/overview': typeof AdminInstanceOverviewRoute
  '/admin/instance/settings': typeof AdminInstanceSettingsRoute
  '/admin/instance/sites': typeof AdminInstanceSitesRoute
  '/admin/instance/users': typeof AdminInstanceUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/admin/instance/': typeof AdminInstanceIndexRoute
  '/admin/site/$siteId/comments': typeof AdminSiteSiteIdCommentsRoute
  '/admin/site/$siteId/integration': typeof AdminSiteSiteIdIntegrationRoute
  '/admin/site/$siteId/members': typeof AdminSiteSiteIdMembersRoute
  '/admin/site/$siteId/settings': typeof AdminSiteSiteIdSettingsRoute
  '/admin/site/$siteId/statistics': typeof AdminSiteSiteIdStatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/confirm-email-change'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/tos'
    | '/widget'
    | '/widget-login'
    | '/admin/instance'
    | '/admin/'
    | '/admin/site/$siteId'
    | '/admin/instance/audit'
    | '/admin/instance/mail'
    | '/admin/instance/overview'
    | '/admin/instance/settings'
    | '/admin/instance/sites'
    | '/admin/instance/users'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/admin/instance/'
    | '/admin/site/$siteId/comments'
    | '/admin/site/$siteId/integration'
    | '/admin/site/$siteId/members'
    | '/admin/site/$siteId/settings'
    | '/admin/site/$siteId/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email-change'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/tos'
    | '/widget'
    | '/widget-login'
    | '/admin'
    | '/admin/site/$siteId'
    | '/admin/instance/audit'
    | '/admin/instance/mail'
    | '/admin/instance/overview'
    | '/admin/instance/settings'
    | '/admin/instance/sites'
    | '/admin/instance/users'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/admin/instance'
    | '/admin/site/$siteId/comments'
    | '/admin/site/$siteId/integration'
    | '/admin/site/$siteId/members'
    | '/admin/site/$siteId/settings'
    | '/admin/site/$siteId/statistics'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/confirm-email-change'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/tos'
    | '/widget'
    | '/widget-login'
    | '/admin/instance'
    | '/admin/'
    | '/admin/site/$siteId'
    | '/admin/instance/audit'
    | '/admin/instance/mail'
    | '/admin/instance/overview'
    | '/admin/instance/settings'
    | '/admin/instance/sites'
    | '/admin/instance/users'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/admin/instance/'
    | '/admin/site/$siteId/comments'
    | '/admin/site/$siteId/integration'
    | '/admin/site/$siteId/members'
    | '/admin/site/$siteId/settings'
    | '/admin/site/$siteId/statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TosRoute: typeof TosRoute
  WidgetRoute: typeof WidgetRoute
  WidgetLoginRoute: typeof WidgetLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email-change': {
      id: '/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-login': {
      id: '/widget-login'
      path: '/widget-login'
      fullPath: '/widget-login'
      preLoaderRoute: typeof WidgetLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instance': {
      id: '/admin/instance'
      path: '/instance'
      fullPath: '/admin/instance'
      preLoaderRoute: typeof AdminInstanceRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/instance/': {
      id: '/admin/instance/'
      path: '/'
      fullPath: '/admin/instance/'
      preLoaderRoute: typeof AdminInstanceIndexRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/audit': {
      id: '/admin/instance/audit'
      path: '/audit'
      fullPath: '/admin/instance/audit'
      preLoaderRoute: typeof AdminInstanceAuditRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/mail': {
      id: '/admin/instance/mail'
      path: '/mail'
      fullPath: '/admin/instance/mail'
      preLoaderRoute: typeof AdminInstanceMailRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/overview': {
      id: '/admin/instance/overview'
      path: '/overview'
      fullPath: '/admin/instance/overview'
      preLoaderRoute: typeof AdminInstanceOverviewRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/settings': {
      id: '/admin/instance/settings'
      path: '/settings'
      fullPath: '/admin/instance/settings'
      preLoaderRoute: typeof AdminInstanceSettingsRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/sites': {
      id: '/admin/instance/sites'
      path: '/sites'
      fullPath: '/admin/instance/sites'
      preLoaderRoute: typeof AdminInstanceSitesRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/instance/users': {
      id: '/admin/instance/users'
      path: '/users'
      fullPath: '/admin/instance/users'
      preLoaderRoute: typeof AdminInstanceUsersRouteImport
      parentRoute: typeof AdminInstanceRouteRoute
    }
    '/admin/site/$siteId': {
      id: '/admin/site/$siteId'
      path: '/site/$siteId'
      fullPath: '/admin/site/$siteId'
      preLoaderRoute: typeof AdminSiteSiteIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site/$siteId/comments': {
      id: '/admin/site/$siteId/comments'
      path: '/comments'
      fullPath: '/admin/site/$siteId/comments'
      preLoaderRoute: typeof AdminSiteSiteIdCommentsRouteImport
      parentRoute: typeof AdminSiteSiteIdRouteRoute
    }
    '/admin/site/$siteId/integration': {
      id: '/admin/site/$siteId/integration'
      path: '/integration'
      fullPath: '/admin/site/$siteId/integration'
      preLoaderRoute: typeof AdminSiteSiteIdIntegrationRouteImport
      parentRoute: typeof AdminSiteSiteIdRouteRoute
    }
    '/admin/site/$siteId/members': {
      id: '/admin/site/$siteId/members'
      path: '/members'
      fullPath: '/admin/site/$siteId/members'
      preLoaderRoute: typeof AdminSiteSiteIdMembersRouteImport
      parentRoute: typeof AdminSiteSiteIdRouteRoute
    }
    '/admin/site/$siteId/settings': {
      id: '/admin/site/$siteId/settings'
      path: '/settings'
      fullPath: '/admin/site/$siteId/settings'
      preLoaderRoute: typeof AdminSiteSiteIdSettingsRouteImport
      parentRoute: typeof AdminSiteSiteIdRouteRoute
    }
    '/admin/site/$siteId/statistics': {
      id: '/admin/site/$siteId/statistics'
      path: '/statistics'
      fullPath: '/admin/site/$siteId/statistics'
      preLoaderRoute: typeof AdminSiteSiteIdStatisticsRouteImport
      parentRoute: typeof AdminSiteSiteIdRouteRoute
    }
  }
}

interface AdminInstanceRouteRouteChildren {
  AdminInstanceAuditRoute: typeof AdminInstanceAuditRoute
  AdminInstanceMailRoute: typeof AdminInstanceMailRoute
  AdminInstanceOverviewRoute: typeof AdminInstanceOverviewRoute
  AdminInstanceSettingsRoute: typeof AdminInstanceSettingsRoute
  AdminInstanceSitesRoute: typeof AdminInstanceSitesRoute
  AdminInstanceUsersRoute: typeof AdminInstanceUsersRoute
  AdminInstanceIndexRoute: typeof AdminInstanceIndexRoute
}

const AdminInstanceRouteRouteChildren: AdminInstanceRouteRouteChildren = {
  AdminInstanceAuditRoute: AdminInstanceAuditRoute,
  AdminInstanceMailRoute: AdminInstanceMailRoute,
  AdminInstanceOverviewRoute: AdminInstanceOverviewRoute,
  AdminInstanceSettingsRoute: AdminInstanceSettingsRoute,
  AdminInstanceSitesRoute: AdminInstanceSitesRoute,
  AdminInstanceUsersRoute: AdminInstanceUsersRoute,
  AdminInstanceIndexRoute: AdminInstanceIndexRoute,
}

const AdminInstanceRouteRouteWithChildren =
  AdminInstanceRouteRoute._addFileChildren(AdminInstanceRouteRouteChildren)

interface AdminSiteSiteIdRouteRouteChildren {
  AdminSiteSiteIdCommentsRoute: typeof AdminSiteSiteIdCommentsRoute
  AdminSiteSiteIdIntegrationRoute: typeof AdminSiteSiteIdIntegrationRoute
  AdminSiteSiteIdMembersRoute: typeof AdminSiteSiteIdMembersRoute
  AdminSiteSiteIdSettingsRoute: typeof AdminSiteSiteIdSettingsRoute
  AdminSiteSiteIdStatisticsRoute: typeof AdminSiteSiteIdStatisticsRoute
}

const AdminSiteSiteIdRouteRouteChildren: AdminSiteSiteIdRouteRouteChildren = {
  AdminSiteSiteIdCommentsRoute: AdminSiteSiteIdCommentsRoute,
  AdminSiteSiteIdIntegrationRoute: AdminSiteSiteIdIntegrationRoute,
  AdminSiteSiteIdMembersRoute: AdminSiteSiteIdMembersRoute,
  AdminSiteSiteIdSettingsRoute: AdminSiteSiteIdSettingsRoute,
  AdminSiteSiteIdStatisticsRoute: AdminSiteSiteIdStatisticsRoute,
}

const AdminSiteSiteIdRouteRouteWithChildren =
  AdminSiteSiteIdRouteRoute._addFileChildren(AdminSiteSiteIdRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminInstanceRouteRoute: typeof AdminInstanceRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSiteSiteIdRouteRoute: typeof AdminSiteSiteIdRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminInstanceRouteRoute: AdminInstanceRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminSiteSiteIdRouteRoute: AdminSiteSiteIdRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TosRoute: TosRoute,
  WidgetRoute: WidgetRoute,
  WidgetLoginRoute: WidgetLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
